### ISSUE TITLE
No way to detect programmatically if signin was unsuccessful.

### ISSUE THREAD

**Issue by shauvik** [GoogleWebComponents/google-signin#111]
The google-signin-aware generates events for successful signin and signout events. However, there is no way to tell if a signin attempt was not successful.

I am working on a single-page application with the google-signin component. 
Case 1. (User already logged in) : Whenever the user is already signed in, I see a signin button for a small time, followed by the signout button. 
Case 2. (User not logged in) : If the user is not logged in, the signin button stays. 

I would like to replace Case 1 with a progressbar, which the google-signin component is doing the background task. However, there is no way to know when the signin was unsuccessful, making it impossible to distinguish between the two cases.

**Comment by atotic** [comment]
I see what the problem is:
- we initialize `signin-aware.isAuthorized` to false
- signinAware only fires success/signed-out events if it's `isAuthorized` status has changed
- on startup, when gapi gets initialized and user is not signed in, `_updateScopeStatus(false)` gets called, but `isAuthorized` is already false, so no events are fired.

Possible fixes are: 
a) not initialize `isAuthorized` flag. This means that flag would be undefined until we know for sure. If user is offline, it would stay undefined forever.
or
b) always fire the events, even if `isAuthorized` did not change. Events would fire every time `GoogleAuth.currentUser.listen` fires. That means that `signin-aware` would fire success/fail events not just when user signes in, but also when additional scopes are granted. There would be no way to distinguish between a signin, and granting of more scopes.

Both of these have drawbacks, and I am not sure which one I'd pick, since I am not a heavy user of the API.

For your problem, there might be a workaround:
- you can display the progress bar until auth2 is loaded. You know that we do not know user state until auth2 is loaded.

**Comment by shauvik** [comment]
Thanks @atotic 

Is there a smart way to check for auth2 being loaded instead of polling using setTimeout ?

**Comment by atotic** [comment]
auth2 is loaded in two stages:
1) gapi: You can wait for gapi loading with <google-js-api>
2) then auth2 by gapi.load(), gets notified of load via callback.

you can wait for 1 via events, then busyWait for auth2. That'd mostly avoid the busywait when auth2 is offline.
