### ISSUE TITLE
Referenced `gapi` doesn't exist

### ISSUE THREAD

**Issue by zoechi** [GoogleWebComponents/google-signin#112]
https://github.com/GoogleWebComponents/google-signin/blob/master/demo/index.html#L129 and lines 141, 145 refer `gapi` but I can't see how this variable declared or initialized.

In https://github.com/GoogleWebComponents/google-signin/blob/master/demo/index.html#L140 `b` is declared but never used.

The selector in lin 140 seems a bit brittle when there are so many `<google-signin> tags in HTML.

I discovered these issues while porting the demos to Polymer for Dart .My JS is weak though and might miss something.

**Comment by Scarygami** [comment]
gapi is loaded as the google-js-api here: https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin-aware.html#L145

**Comment by zoechi** [comment]
Thanks, than it's my limited JS knowledge. 
So it somehow becomes a global variable?
If you think there is still work to do you can reopen. I think I know what I have to do in the Dart port.
Thanks again :)

**Comment by Scarygami** [comment]
Yes `gapi` becomes a global variable when the Google JS client library is loaded.

When porting the element to Dart you can try to depend on the [`googleapis_auth`](https://github.com/dart-lang/googleapis_auth) package which also uses `gapi` in the background.
It still uses the old `gapi.auth` methods instead of `gapi.auth2` though, so calls would be quite different.

**Comment by zoechi** [comment]
Ok, I guess I try dart-js-interop first.
