### ISSUE TITLE
Old scopes are requested on signIn.(not reset)

### ISSUE THREAD

**Issue by satoshun00** [GoogleWebComponents/google-signin#114]
To reproduce this on demo,
1. Sign in with set scope param to `None`
2. Change scope to `Google Plus view circles` (not go sign in)
3. Change scope to `None` and go sign in

-> App has request `Google Plus view circles`.

Is this correct behavior??

**Comment by atotic** [comment]
We've judged that scope removal is an unusual case that will not be handled. The way most apps operate is that their scope expands, not contract.
Scope removal complexity includes:
- keeping tally of how many times each scope was registered.
- what happens if granted scope gets unregistered? Should be reset our authorization?
- if google-signin-aware elements are attached/detached dynamically, scopes switch between active/inactive states....
Just more trouble than it was worth.
