### ISSUE TITLE
gapi.auth2.ExternallyVisibleError

### ISSUE THREAD

**Issue by curtiscovington** [GoogleWebComponents/google-signin#138]
I can't see to get google-signin-aware to work properly. If it appears right under my google-signin element it works fine, but if it is in another element, like the google-sheets element, or my custom elements, I get the gapi.auth2 error.

`cb=gapi.loaded_0:64 Uncaught gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().`

**Comment by atotic** [comment]
I suspect that your usage causes the error. Can you create a reproducible case we can look at?

**Comment by LM450N** [comment]
I already got the same error. In my case I was using two `google-signin` elements at two different places in my app but only the first one was defining the client ID. After have set the same client ID on both elements everything worked well.

I guess the reason is you have multiple instances of `google-signin-aware` in your app and one of them is not [initialized](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin-aware.html#L226) like the others.

**Comment by atotic** [comment]
Found the cause. Setting the clientId always calls initAuth. I'll fix it.

**Comment by LM450N** [comment]
Thank you for this fix !

**Comment by sudipstha08** [comment]
I am getting this error in next js. Am i doing sth wrong ?

```js
const loadClient = async () => {
    try {
      setLoading(true)
      await window["gapi"]?.client.setApiKey(API_KEY)
      await window["gapi"].client.load(
        "https://content.googleapis.com/discovery/v1/apis/calendar/v3/rest",
        "v3"
      )
      setLoading(false)
    } catch (err) {
      setLoading(false)
    }
  }
```

```js
const isSignedIn = window["gapi"]?.auth2?.getAuthInstance()?.isSignedIn?.get()

 useEffect(() => {
    window["gapi"]?.load("client:auth2", async () => {
      try {
        setLoading(true)
        if (!isSignedIn) {
          await window["gapi"]?.auth2.init({
            client_id: CLIENT_ID,
            scope: scope,
          })
          await loadClient()
        }
        setLoading(false)
      } catch (err) {
        setLoading(false)
      }
    })
  }, [])
```
