### ISSUE TITLE
Fetch scopes, don't cache them

### ISSUE THREAD

**Issue by beriberikix** [GoogleWebComponents/google-signin#25]
Storing an array of scopes is a bit flaky as it only accounts for calls made in the same session (See [here](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L179) and [here](https://github.com/GoogleWebComponents/google-signin/blob/master/google-signin.html#L143).)

Either call gapi.auth.getToken() or hit the [Tokeninfo endpoint](https://developers.google.com/accounts/docs/OAuth2UserAgent#validatetoken). Note that due to a feature limitation, checking scopes might not be synchronized if they modified on another client (like on Android or iOS.) The only way to fully know is to try and to authorize.

**Comment by Zoramite** [comment]
With the latest update to `0.3.0` a lot of the internals have changed regarding how the the scopes are retrieved and manipulated. The `signin` element does not do any caching itself, instead it relies on the identity iframe to handle the caching.

I believe this issue is no longer relevant with the underlying changes.

An interesting experiment, watch what happens when you have two tabs open that are using the same client id to authenticate with the `<google-signin>` elements on both tabs. :smile_cat:
